### ISSUE TITLE
Anim jumpy/jiggering appear on 3.11.0

### ISSUE THREAD

**Issue by Makio64** [greensock/GSAP#513]
Hi, 

I updated my project from 3.10.4 to 3.11 and some animation I'm using became jiggering / jumpy when it was all smooth before. I reverted to 3.10.4 and the bugs goes away.

here a simplify example of the kind of anim who get jiggery in the 3.11.0, not sure if its cause by the `set` or the fact there is 2 anim with a delay on the same element.
 
```
	mounted() {
		gsap.set(this.baguette, { rotate: 55, x: 200, y: -40 })
		gsap.from(this.baguette, { duration: 0.5, x: 200 + Math.cos(angle) * -500, y: -40 + Math.sin(angle) * -150, delay: 0.6 })
		gsap.from(this.baguette, { duration: 0.6, rotate: 75, delay: 0.8})
	}
```

**Comment by jackdoyle** [comment]
It's pretty tough to troubleshoot without a minimal demo - can you provide a very simple CodePen please? 

There was a regression related to SVG transforms in 3.11.0 which has been resolved in the upcoming release that you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

Does the problem you're experiencing go away after you update to that file above?

**Comment by Makio64** [comment]
Sorry, I'm currently importing it using the following synthax: 
`import { gsap, Quad } from 'gsap/gsap-core'`

Is there a way to test the patch with this synthax?

Also my problem is probably related to the fact the transform are apply to "rotate" and " x/y" independently + a setting at the start ( not sure it changes anything ) and it doesnt involve svg as far as I know.

I report it to let you know there is a bug in the latest but I dont have extra time to investigate and create minimal reproducing example ( as I'm not totally sure which part broke with the latest version ) sorry!

**Comment by jackdoyle** [comment]
Please try the latest official release (3.11.1) and verify that the issue is resolved.

**Comment by Makio64** [comment]
Thanks, I just try but the same bug is happening, once I update to the 3.11.1 some of my animations ( complex one with rotate / transform and different timing delay etc.. ) start to become jittering..

**Comment by jackdoyle** [comment]
@Makio64 please provide a minimal demo and we'd be happy to take a look at any GSAP-related questions. A CodePen with only the smallest amount of code to illustrate the issue is best. A CodeSandbox is okay too.

**Comment by jackdoyle** [comment]
You can update to 3.11.2 (just released) and if you notice any issues, let us know. A minimal demo would be SUPER helpful.

**Comment by Makio64** [comment]
The jumping bug is still there during one frame ( I guess first frame of the rotate anim ) if I do this : 

```
gsap.set(obj, {x , y, rotate} )
gsap.from(obj, {x:0 , y:0, delay:0.5} )
gsap.from(obj, {rotate:0, delay:0.65} )
```

if i do the opposite logic ( set the from and then use gsap.to. see after ) no problem in 3.11.2

```
gsap.set(obj, {x:0, y:0, rotate:0} )
gsap.to(obj, {x, y, delay:0.5} )
gsap.to(obj, {rotate, delay:0.65} )

**Comment by jackdoyle** [comment]
Are you saying you see something "jump" here?: 
https://codepen.io/GreenSock/pen/oNdqwbL?editors=0010

**Comment by Makio64** [comment]
Hello, yes, I just tried on my computer ( windows / RTX 3090 Ti ) and time to time yes ( maybe once on 8 ? ), you see it rotated at the start of the anim for one frame.
I guess on my app its more obvious probably cause more stuffs are happening and main thread is busier.

**Comment by jackdoyle** [comment]
Can you please try using this beta version of GSAP and let me know if you see the same thing? I cannot see any rendering problems at all, even in 3.11.2 so I'm struggling to understand what the issue might be on your end. 
https://assets.codepen.io/16327/gsap-latest-beta.min.js

(you may need to clear your cache)
